version: '3.8'
services:
  Elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    container_name: elasticsearch
    restart: always
    volumes:
      - ./elasticsearch/data/:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: '-Xmx128m -Xms128m'
      discovery.type: single-node
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - elk
    deploy:
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 100M

  Logstash:
    image: docker.elastic.co/logstash/logstash:7.13.3
    container_name: logstash
    restart: always
    volumes:
      - ./logstash/:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf
    depends_on:
      - Elasticsearch
    ports:
      - '9600:9600'
      - '5000:5000'
    environment:
      LS_JAVA_OPTS: '-Xmx128m -Xms128m'
    networks:
      - elk
    deploy:
      resources:
        limits:
          memory: 150M
        reservations:
          memory: 50M

  Kibana:
    image: docker.elastic.co/kibana/kibana:7.13.3
    container_name: kibana
    restart: always
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - Elasticsearch
    networks:
      - elk
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 50M
volumes:
  elastic_data: {}

networks:
  elk:
